config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  resources :users
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord

  # Define association with user
  belongs_to :user
  # Validate for title
  validates :title, presence: true, length: { in: 5..100 }
  
  # Validate for content
  validates :content, presence: true, length: { in: 5..1000 } 
end

app/models/user.rb
class User < ApplicationRecord

  # Sure that email of user must lowercase format before it is saved to database
  before_save { email.downcase! }

  # Format of email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # Validate name of user must be presence, length of name
  validates :name, presence: true, length: { maximum: 50 }

  #  Validate email of user must be presence, length of email
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false } 
  
  # Add secure password for user
  has_secure_password

  #  Validate for password of user
  validates :password, presence: true, length: { minimum: 6 }

  # Define association with micropost
  has_many :microposts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  def index
    @microposts = Micropost.all
  end

  def show
  end

  def new
    @micropost = Micropost.new
  end

  def edit
  end

  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    def micropost_params
      params.require(:micropost).permit(:title, :content, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @microposts = Micropost.all
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def show
    if @user.microposts.any?
      @microposts_user = @user.microposts.order(created_at: :desc)
    else
      @microposts_user = 0
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basic.
  def full_title(page_title = '')
    base_title = "Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end 
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer__logo-box">
    <%= image_tag("logo-red.png", alt: "LOGO-RED", class: "footer__logo") %>
  </div>

  <div class="row">
    <div class="col-1-of-2">
      <div class="footer__navigation">
        <ul class="footer__list">
          <li class="footer__item"><%= link_to 'About', static_pages_about_path, class: "footer__link" %></li>
          <li class="footer__item"><%= link_to 'Help', static_pages_help_path, class: "footer__link" %></li>
          <li class="footer__item"><%= link_to 'Contributors', users_path, class: "footer__link" %></li>
          <li class="footer__item"><%= link_to 'Microposts', microposts_path, class: "footer__link" %></li>
        </ul>
      </div>
    </div>

    <div class="col-1-of-2">
      <p class="footer__copyright">
        Built by <%= link_to 'LTViet', "http://sample_app.test/" %> for learning Ruby on Rails by doing project &copy; 2019
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="header__logo-box">
    <%= image_tag("logo-white.png", alt: "LOGO WHITE", class: "header__logo") %>
  </div>

  <div class="header__text-box">
    <h1 class="heading-primary">
      <span class="heading-primary--main">Sample App</span>
      <span class="heading-primary--sub">with Ruby on Rails</span>
    </h1>
    <%= link_to 'Discover Our MicroPosts', root_path, class: "btn btn--white btn--animated" %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: "form-control", placeholder: "Enter name of title" %>
  </div>

  <div class="form-group">
    <%= form.text_area :content, class: "form-control", placeholder: "Enter content of post" %>
  </div>

  <div class="form-group">
    <%= form.text_field :user_id, class: "form-control", placeholder: "Enter ID of author" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn--wthite btn--animated" %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<table class="table custom-table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col-span-3">More Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', micropost_path(post) %></td>
        <td><%= link_to 'Edit', edit_micropost_path(post) %></td>
        <td><%= link_to 'Remove', micropost_path(post), method: :delete, data: { confirm: "Are you sure remove this post?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/microposts/edit.html.erb
<% provide(:title, "Edit Post") %>
<section class="section-micropost">
  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      Edit Post 
    </h2>
  </div>

  <div class="row">
    <p class="paragraph u-justify-text">
    <%= render 'form', micropost: @micropost %>
    <%= link_to 'Show', @micropost, class: "short-link"  %> |
    <%= link_to 'Back', microposts_path, class: "short-link" %>
    </p>
  </div>
</section>

app/views/microposts/index.html.erb
<% provide(:title, "Microposts") %>
<section class="section-microposts">
  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      All Microposts
    </h2>
  </div>

  <div class="row">
    <%= render 'microposts/micropost' %>
  </div>
</section>

app/views/microposts/new.html.erb
<% provide(:title, "New Post") %>
<section class="section-micropost">
  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      New Post
    </h2>
  </div>

  <div class="row">
    <p class="paragraph u-justify-text">
    <%= render 'form', micropost: @micropost %>
    <%= link_to 'Back', microposts_path, class: "short-link" %>
    </p>
  </div>
</section>

app/views/microposts/show.html.erb
<% provide(:title, "Post") %>
<section class="section-micropost">
  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      Detail Post
    </h2>
  </div>

  <div class="row">
    <h4 class="u-center-text title-post"><%= @micropost.title %></h4>
    <p class="paragraph">
      <%= @micropost.content %>
    </p>

    <p class="paragraph u-center-text">
      <%= link_to 'Edit Post', edit_micropost_path(@micropost), class: "btn btn-primary" %>
      <%= link_to 'Remove Post', micropost_path(@micropost), method: :delete, data: { confirm: "Are you sure remove this post?" }, class: "btn btn-warning" %>
    </p>
  </div>
</section>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<section class="section-about">
  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      Learn Web Development with Rails
    </h2>
  </div>

  <div class="row">
    <p class="paragraph u-justify-text">
      "Ruby on Rails Tutorial" by <strong>Michael Hartl</strong> has become a must-read for developers learning how to build Rails apps. "Peter Cooper, Editor of" Ruby Inside Using Rails, developers can build web applications of exceptional elegance and power. Although its remarkable capabilities have made Ruby on Rails one of the world s most popular web development frameworks, it can be challenging to learn and use. " Ruby on Rails Tutorial, Second Edition, " is the solution. Best-selling author and leading Rails developer Michael Hartl teaches Rails by guiding you through the development of your own complete sample application using the latest techniques in Rails web development.
    </p>

    <p class="paragraph u-justify-text">
      The updates to this edition include all-new site design using Twitter s Bootstrap; coverage of the new asset pipeline, including Sprockets and Sass; behavior-driven development (BDD) with Capybara and RSpec; better automated testing with Guard and Spork; roll your own authentication with has_secure_password; and an introduction to Gherkin and Cucumber. You'll find integrated tutorials not only for Rails, but also for the essential Ruby, HTML, CSS, JavaScript, and SQL skills you'll need when developing web applications.
    </p>

    <p class="paragraph u-justify-text">
      Hartl explains how each new technique solves a real-world problem, and he demonstrates this with bite-sized code that s simple enough to understand, yet novel enough to be useful. Whatever your previous web development experience, this book will guide you to true Rails mastery. This book will help you.
    </p>

    <p class="paragraph u-justify-text">
      Install and set up your Rails development environment Go beyond generated code to truly understand how to build Rails applications from scratch Learn test-driven development (TDD) with RSpec Effectively use the Model-View-Controller (MVC) pattern Structure applications using the REST architecture Build static pages and transform them into dynamic ones Master the Ruby programming skills all Rails developers need Define high-quality site layouts and data models Implement registration and authentication systems, including validation and secure passwords Update, display, and delete users Add social features and microblogging, including an introduction to Ajax Record version changes with Git and share code at GitHub Simplify application deployment with Heroku.
    </p>
  </div>

  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      Ruby on Rails Guide Official
    </h2>
  </div>

  <div class="row">
    <p class="paragraph u-justify-text">
      The official guides created by Ruby on Rails contributors. A good starting point on this site for beginners is Getting Started with Rails. It also has tutorials on learning the foundations of Models, Views, and Controllers — including routing.
    </p>
  </div>
</section>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<section class="section-help">
  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      Help
    </h2>
  </div>

  <div class="row">
    <p class="paragraph u-justify-text">
      Get help on the Ruby on Rails Tutorial at the <%= link_to 'Rails Tutorial help page', "https://www.railstutorial.org/help", class: "section-help__link"%> .
      To get help on this sample app, see the <em><%= link_to 'Ruby on Rails Tutorial', "https://www.railstutorial.org/book", class: "section-help__link" %></em> book.
    </p>
  </div>
</section>

app/views/static_pages/home.html.erb
<main>
  <section class="section-about">
    <div class="u-center-text u-margin-bottom-big">
      <h2 class="heading-secondary">
        Exciting Framework Web for beginner
      </h2>
    </div>

    <div class="row">
      <div class="col-1-of-2">
        <h3 class="heading-tertiary u-margin-bottom-small">Ruby on Rails Tutorial Book</h3>
        <p class="paragraph">
          The <a href="http://www.railstutorial.org/">is a tutorial for teaching
          web development with Ruby on Rails.</a>
        </p>

        <p>This application is build base on this tutorial.</p>

        <h3 class="heading-tertiary u-margin-bottom-small">Ruby on Rails Guide</h3>
        <p class="paragraph">
          The <a href="https://guides.rubyonrails.org/">is an official guide of Ruby on Rails.</a>
        </p>

        <p>Reference it if you want to learn more about Ruby on Rails.</p>
        <%= link_to "More <span>&rarr;</span>".html_safe, static_pages_about_path, class: "btn-text" %>
      </div>

      <div class="col-1-of-2">
        <div class="composition">
          <%= image_tag("rails-welcome.png", alt: "Rails welcome", class: "composition__photo composition__photo--p1 ") %>
          <%= image_tag("rails.jpg", alt: "Rails", class: "composition__photo composition__photo--p2 ") %>
          <%= image_tag("rails-component.png", alt: "Rails component", class: "composition__photo composition__photo--p3 ") %>
        </div>
      </div>
    </div>
  </section>

  <section class="section-microposts">
    <div class="u-center-text u-margin-bottom-big">
      <h2 class="heading-secondary">
        All MicroPosts
      </h2>
    </div>

    <div class="row">
    <%= render 'microposts/micropost' %>
    </div>
  </section>
</main>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name, class: "form-control", placeholder: "Enter Your Name" %>
  </div>

  <div class="form-group">
    <%= form.text_field :email, class: "form-control", placeholder: "Enter Your Email" %>
  </div>

  <div class="form-group">
    <%= form.password_field :password, class: "form-control", placeholder: "Enter Your Password" %>
  </div>

  <div class="form-group">
  <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Retype Your Password to Confirm" %>
</div>

  <div class="actions">
    <%= form.submit class: "btn btn--white btn--animated" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<section class="section-user">
  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      Edit User
    </h2>
  </div>

  <div class="row">
    <p class="paragraph u-justify-text">
    <%= render 'form', user: @user %>
    <%= link_to 'Show', @user, class: "short-link" %> | <%= link_to 'Back', users_path, class: "short-link" %>
    </p>
  </div>
</section>

app/views/users/index.html.erb
<% provide(:title, "Contributors") %>
<section class="section-users">
  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      Contributors
    </h2>
  </div>

  <div class="row">
    <table class="table custom-table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col-span-3">More Actions</th>
        </tr>
      </thead>
    
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= link_to 'Show', user_path(user) %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Remove', user_path(user), method: :delete, data: { confirm: "Are you sure remove this user?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/users/new.html.erb
<% provide(:title, "New User") %>
<section class="section-user">
  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      New User
    </h2>
  </div>

  <div class="row">
    <p class="paragraph u-justify-text">
    <%= render 'form', user: @user %>
    <%= link_to 'Back', users_path, class: "short-link" %>
    </p>
  </div>
</section>

app/views/users/show.html.erb
<% provide(:title, "User") %>
<section class="section-user">
  <div class="u-center-text u-margin-bottom-big">
    <h2 class="heading-secondary">
      Information
    </h2>
  </div>

  <div class="row">
    <p class="paragraph u-center-text">
      Name: 
      <%= @user.name %>
    </p>

    <p class="paragraph u-center-text">
      Email: 
      <%= @user.email %>
    </p>

    <p class="paragraph u-center-text">
      <%= link_to 'Edit User', edit_user_path(@user), class: "btn btn-primary" %>
      <%= link_to 'Remove User', user_path(@user), method: :delete, data: { confirm: "Are you sure remove this user?" }, class: "btn btn-warning" %>
    </p>
    <hr>
    <h3 class="u-center-text"> All Posts of User</h3>
    <% unless @microposts_user == 0 %>
      <% @microposts_user.each do |post| %>
        <h4 class="u-center-text title-post"><%= post.title %></h4>
        <p class="paragraph">
          <%= post.content %>
        </p>

        <p class="paragraph u-center-text">
        <%= link_to 'Show Post', micropost_path(post), class: "btn btn-success" %>
          <%= link_to 'Edit Post', edit_micropost_path(post), class: "btn btn-primary" %>
          <%= link_to 'Remove Post', micropost_path(post), method: :delete, data: { confirm: "Are you sure remove this post?" }, class: "btn btn-warning" %>
        </p>
      <% end %>
    <% else %>
      <p class="paragraph u-center-text">
        You don't have any post, so do you want to create post?
        <%= link_to 'Click here', new_micropost_path, class: "short-link" %>
      </p>
    <% end %>
  </div>
</section>